@extends('layouts.site')

@section('container')
    <div class="container my-3">
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Pol&iacute;tica de Privacidade&nbsp;</strong></p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><span style="background: #ffffff;">Quando voc&ecirc; realiza uma compra na Preservando voc&ecirc; nos fornece alguns dados pessoais com o objetivo de viabilizar a sua opera&ccedil;&atilde;o.&nbsp;</span></p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><span style="background: #ffffff;">A Preservando preza pela seguran&ccedil;a dos seus dados, pelo respeito a sua privacidade e pela transpar&ecirc;ncia com voc&ecirc; e, por isso, dedicamos este documento para explicar como os seus dados pessoais ser&atilde;o tratados pela Preservando e quais s&atilde;o as medidas que aplicamos para mant&ecirc;-los seguros.</span></p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><span style="background: #ffffff;">Antes de mais nada, nos apresentamos, n&oacute;s somos&nbsp;</span><strong>Preservando Folhagens Preservadas e Decora&ccedil;&otilde;es LTDA</strong><span style="background: #ffffff;">, inscrito no&nbsp;</span><strong>CNPJ 44.192.782/0001-83</strong><span style="background: #ffffff;">, com sede na Cidade de Guarulhos, Estado de S&atilde;o Paulo, na Avenida Presidente Humberto de Alencar Castelo Branco n&ordm; 3863, Bairro Vila Leonor CEP 07.024-170 e segundo a defini&ccedil;&atilde;o trazida pela Lei Geral de Prote&ccedil;&atilde;o de Dados &ldquo;LGPD&rdquo; (Lei Federal n&ordm; 13.709.2018), na maior parte do tempo seremos o controlador das suas informa&ccedil;&otilde;es, sendo assim, respons&aacute;vel por definir o que acontece com estes dados e por proteg&ecirc;-los. Para facilitar a compreens&atilde;o desta pol&iacute;tica, todas as vezes que encontrar os termos &ldquo;Preservando&rdquo;, &ldquo;n&oacute;s&rdquo; ou &ldquo;nossos&rdquo;, estamos nos referindo ao controlador dos seus dados pessoais, ou seja, &agrave; empresa Preservando e, todas as vezes que ler &ldquo;usu&aacute;rio&rdquo;, &ldquo;voc&ecirc;&rdquo;, &ldquo;seu&rdquo; ou &ldquo;sua&rdquo;, nos referimos a voc&ecirc;, nosso cliente ou usu&aacute;rio da nossa plataforma.</span></p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><strong><span style="background: #ffffff;">QUAIS DADOS S&Atilde;O COLETADOS PELA PRESERVANDO?</span></strong></p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><span style="background: #ffffff;">Durante sua experi&ecirc;ncia no nosso site podemos coletar diferentes tipos de dados pessoais, de forma autom&aacute;tica com o objetivo de confer&ecirc;ncia, monitoramento e controle, ou fornecidas diretamente por voc&ecirc;, como por exemplo para a realiza&ccedil;&atilde;o de seu cadastro. Veja abaixo quais dados pessoais n&oacute;s podemos coletar e em cada situa&ccedil;&atilde;o:</span></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Durante o cadastro:</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Nome completo;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">N&uacute;mero de CPF;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Endere&ccedil;o de e-mail;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">N&uacute;mero de celular;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Data de Nascimento;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Dados referentes aos seus endere&ccedil;os;</p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;">Esses dados t&ecirc;m por objetivo ajudar na sua experiencia de compra, e os produtos adquiridos por meio da PRESERVANDO.COM.BR sejam enviados de forma correta e segura.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Durante o preenchimento do local de entrega e forma de pagamento:</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Endere&ccedil;o de cobran&ccedil;a;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Endere&ccedil;o de entrega;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Dados do cart&atilde;o de cr&eacute;dito, quando escolhido como forma de pagamento.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Durante a an&aacute;lise e o monitoramento de suas compras ou outras transa&ccedil;&otilde;es financeiras:</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Dados cadastrais;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Tipo de produto;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Quantidade;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Valor da mercadoria (unit&aacute;rio);</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Valor total da compra ou transa&ccedil;&atilde;o;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Natureza da transa&ccedil;&atilde;o financeira;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&otilde;es da conta banc&aacute;ria e outros meios utilizados.</p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;">As transa&ccedil;&otilde;es financeiras que acontecem na plataforma Preservando &eacute; de responsabilidade da empresa terceira especializada em meios de pagamentos, que ocorrem de forma digital, a <strong>Pagar.me Pagamentos S.A. (CNPJ n&ordm; 18.727.053/0001-74)</strong>. A Pargar.me segue as diretrizes segundo a LGPD, e voc&ecirc; pode conferir mais detalhes acessando, <u><a href="https://www.pagar.me/aviso-de-privacidade/">https://www.pagar.me/aviso-de-privacidade/</a></u>.<u>&nbsp;</u></p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;">Abaixo apresentamos as informa&ccedil;&otilde;es que poder&atilde;o ser coletadas mesmo que o Usu&aacute;rio n&atilde;o esteja cadastrado na loja virtual da Preservando:</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Durante a Navega&ccedil;&atilde;o na Plataforma:</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Endere&ccedil;o de IP;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&otilde;es sobre o dispositivo utilizado para a navega&ccedil;&atilde;o;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Produtos e categorias pesquisados ou visualizados;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Contagem de visualiza&ccedil;&otilde;es;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Outras informa&ccedil;&otilde;es que poder&atilde;o ser coletadas:</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&otilde;es de Login social, caso voc&ecirc; realize seu cadastro por meio de uma conta em rede social, como Facebook e Google, e autorize essa coleta;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&otilde;es sobre voc&ecirc; que ser tornaram p&uacute;blicas por voc&ecirc; ou que estejam dispon&iacute;veis publicamente;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&otilde;es que coletamos de terceiros, como por exemplo, complementos dos seus dados cadastrais (nome, filia&ccedil;&atilde;o, data de nascimento, CPF, n&uacute;mero de telefone, entre outros), score gerado por ag&ecirc;ncias de cr&eacute;dito, se voc&ecirc; faz parte de alguma lista de Pessoa Exposta Politicamente (PEP) ou de algumas lista de alerta (como OFAC, CSNU e outras listas internacionais), entre outras;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&otilde;es que recebemos de parceiros para entrega de produtos adquiridos nas plataformas parceiras da Preservando como, por exemplo, resgate de produtos em programa de fidelidade ou qualquer outra plataforma em que a Preservando possa ofertar seu cat&aacute;logo de produtos;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&otilde;es fornecidas por voc&ecirc; voluntariamente, como por de meio de comunica&ccedil;&otilde;es com a Preservando em redes sociais ou em coment&aacute;rios e avalia&ccedil;&otilde;es de produtos.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>COMO N&Oacute;S UTILIZAMOS SEUS DADOS PESSOAIS?</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">N&oacute;s utilizamos os dados pessoais para garantir um atendimento de qualidade e uma melhor experi&ecirc;ncia na sua compra. Listamos abaixo as finalidades que poderemos utilizar seus dados pessoais:</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Dados cadastrais:</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para viabilizar a presta&ccedil;&atilde;o de diferentes servi&ccedil;os dispon&iacute;veis na nossa loja virtual;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para realizar o atendimento de solicita&ccedil;&otilde;es e d&uacute;vidas em nossa Central de Atendimento;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para identificar corretamente o Usu&aacute;rio;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para enviar os produtos adquiridos ou comunica&ccedil;&otilde;es de ofertas;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para entrar em contato com voc&ecirc;, quando necess&aacute;rio. Esse contato pode contemplar diversos assuntos, como comunica&ccedil;&atilde;o sobre promo&ccedil;&otilde;es e ofertas, respostas a d&uacute;vidas, respostas de reclama&ccedil;&otilde;es e ofertas, respostas a d&uacute;vidas, respostas de reclama&ccedil;&otilde;es e solicita&ccedil;&otilde;es, atualiza&ccedil;&otilde;es dos pedidos realizados e informa&ccedil;&otilde;es de entrega;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para auxiliar no diagn&oacute;sticos e solu&ccedil;&atilde;o de problemas t&eacute;cnicos;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para desenvolver novas funcionalidades e melhorias, melhorando a sua experi&ecirc;ncia com nossos servi&ccedil;os dispon&iacute;veis;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para consultar suas informa&ccedil;&otilde;es nas bases de dados de ag&ecirc;ncias de cr&eacute;ditos;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para realizar investiga&ccedil;&otilde;es e medidas de preven&ccedil;&atilde;o e combate a il&iacute;citos, fraudes, crimes financeiros e crimes de lavagem de dinheiro e/ou de financiamento ao terrorismo;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para garantir o comprimento de obriga&ccedil;&atilde;o legal ou regulat&oacute;ria ou garantir o exerc&iacute;cio regular de direitos da Preservando. Nesses casos, podemos, inclusive, utilizar e apresentar as informa&ccedil;&otilde;es em processos judiciais e administrativos, se necess&aacute;rio;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para colaborar com o cumprimento de ordem judicial, de autoridade competente ou de &oacute;rg&atilde;o fiscalizador.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Dados de Navega&ccedil;&atilde;o:</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para auxiliar no diagn&oacute;stico e solu&ccedil;&atilde;o de problemas t&eacute;cnicos;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para desenvolver novas funcionalidades e melhorias, melhorando a sua experi&ecirc;ncia com nossos servi&ccedil;os dispon&iacute;veis.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="margin-bottom: 0.28cm;line-height: 108%;text-align: left;background: transparent;"><strong>COM QUEM N&Oacute;S PODEMOS COMPARTILHAR OS DADOS PESSOAIS?</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Para a execu&ccedil;&atilde;o das atividades acima listadas, sempre que necess&aacute;rio, n&oacute;s poderemos compartilhar os seus dados pessoais com prestadores de servi&ccedil;o, parceiros ou com &oacute;rg&atilde;os reguladores. Jamais comercializamos dados pessoais. Apresentamos a seguir um resumo destas possibilidades:</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Prestadores de Servi&ccedil;os:</strong> para que possamos disponibilizar nossos produtos e prestar os nossos servi&ccedil;os com qualidade, contamos com a colabora&ccedil;&atilde;o de diversos prestadores de servi&ccedil;o, que tratam os dados pessoais coletados em nosso nome e de acordo com nossas instru&ccedil;&otilde;es. Esses prestadores de servi&ccedil;o atuam principalmente para nos nas an&aacute;lises antifraude, intermedia&ccedil;&atilde;o de pagamentos, gest&atilde;o de campanhas de marketing, enriquecimento de base de dados e armazenamento em nuvem, transporte de mercadorias e armazenamento de dados em nuvem (Hospedagem do site em Servidor).</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Autoridades judiciais, policiais ou governamentais:</strong> n&oacute;s devemos fornecer dados pessoais de Clientes e/ou Usu&aacute;rios, em atendimento &agrave; ordem judicial, solicita&ccedil;&otilde;es de autoridades administrativas, obriga&ccedil;&atilde;o legal ou regulat&oacute;ria, bem como para agir de forma colaborativa com autoridades governamentais, em geral em investiga&ccedil;&otilde;es envolvendo atos il&iacute;citos.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>Potenciais compradores:</strong> podemos compartilhar seus dados pessoais com outras empresas as quais a Preservando conclua uma negocia&ccedil;&atilde;o de venda ou transfer&ecirc;ncia de parte ou totalidade da atividade comercial, neg&oacute;cio ou opera&ccedil;&atilde;o da Preservando. Caso a venda ou transfer&ecirc;ncia n&atilde;o sejam consumadas, solicitaremos ao potencial comprador que n&atilde;o fa&ccedil;a uso e n&atilde;o divulgue seus dados pessoais de qualquer maneira ou forma, apagando-os por completo.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>ARMAZENAMENTO E SEGURAN&Ccedil;A DOS DADOS PESSOAIS</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">N&oacute;s armazenamos seus dados de forma segura em data centers localizados no Brasil, bem como no exterior. Neste caso de armazenamento no exterior, s&atilde;o adotadas todas as medidas leais aplic&aacute;veis, em conformidade com a Lei Geral de Prote&ccedil;&atilde;o de Dados (LGPD) e suas futuras regulamenta&ccedil;&otilde;es, garantindo a prote&ccedil;&atilde;o e privacidade dos seus dados pessoais.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">N&oacute;s adotamos as melhores para proteger os dados pessoais coletados de acesso n&atilde;o autorizados, destrui&ccedil;&atilde;o, perda, altera&ccedil;&atilde;o, comunica&ccedil;&atilde;o ou qualquer forma de tratamento inadequado ou il&iacute;cito, inclusive mecanismos de criptografia.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Ressaltamos, contudo, que nenhuma plataforma &eacute; completamente segura. Se voc&ecirc; tiver qualquer preocupa&ccedil;&atilde;o ou suspeita de que os seus dados estejam em risco, por favor, entre em contato conosco por meio dos nossos canais de atendimento que ficaremos felizes em te responder ou auxiliar prontamente.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Seus dados pessoais ser&atilde;o mantidos durante todo o per&iacute;odo que for um cliente ativo Preservando. Ap&oacute;s esse per&iacute;odo, podemos armazenar os seus dados pessoais por um per&iacute;odo adicional para fins de auditoria, para possibilitar o cumprimento de obriga&ccedil;&otilde;es legais ou regulat&oacute;rias. Faremos a reten&ccedil;&atilde;o dos seus dados pelo prazo necess&aacute;rios, respeitando os prazos estabelecidos na legisla&ccedil;&atilde;o aplic&aacute;vel.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>COOKIES E TECNOLOGIA DE MONITORAMENTO</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;">Podemos utilizar certas tecnologias de monitoramento para coletar informa&ccedil;&otilde;es das atividades realizadas em nosso site de forma automatizada. As informa&ccedil;&otilde;es coletadas por meio de tais tecnologias s&atilde;o utilizadas para realizar m&eacute;tricas de performance do site, identificar problemas no uso, captar o comportamento dos Usu&aacute;rios de forma geral e coletar dados de impress&atilde;o de conte&uacute;dos. Veja abaixo algumas tecnologias que poder&atilde;o estar presentes no site da Preservand:</p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><strong>Cookies:</strong> cookie &eacute; um pequeno arquivo adicionado ao dispositivo do Usu&aacute;rio para fornecer uma experi&ecirc;ncia personalizada de acesso &agrave; plataforma. Os cookies ajudam a analisar o tr&aacute;fego de internet e nos permite saber quando o Usu&aacute;rio visitou um site espec&iacute;fico. Um cookie n&atilde;o d&aacute; acesso a um computador ou revela informa&ccedil;&otilde;es al&eacute;m dos dados que o Usu&aacute;rio escolhe compartilhar conosco.</p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><strong>Pixels:</strong> pixels s&atilde;o partes do c&oacute;digo JavaScript instalados adicionados em nossas aplica&ccedil;&otilde;es, websites ou no corpo de um e-mail, com a finalidade de rastrear e coletar informa&ccedil;&otilde;es sobre as atividades dos Usu&aacute;rios, permitindo a identifica&ccedil;&atilde;o sobre as atividades dos Usu&aacute;rios, permitindo a identifica&ccedil;&atilde;o dos seus padr&otilde;es de acesso, navega&ccedil;&atilde;o, interesse de compras de produtos, e utilizados para otimizar o direcionamento de conte&uacute;do.</p>
        <p style="text-align: justify;background: transparent;text-indent: 1.25cm;margin-bottom: 0.28cm;line-height: 108%;"><strong>Ferramentas de Analytics</strong>: essas ferramentas podem coletar informa&ccedil;&otilde;es sobra a forma como os Usu&aacute;rios visitam nosso site, quais p&aacute;ginas eles visitam e quando visitam tais p&aacute;ginas, outros sites que foram visitados antes, entre outras.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>TRANSFER&Ecirc;NCIA INTERNACIONAL DE DADOS PESSOAIS&nbsp;</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Alguns de seus dados pessoais poder&atilde;o ser transferidos para outros pa&iacute;ses, por exemplo, quando utilizarmos servi&ccedil;os computacionais em nuvem para processamento ou armazenamento de dados, localizados fora do Brasil. Mas n&atilde;o se preocupe, a Preservando observa tamb&eacute;m nessas situa&ccedil;&otilde;es todos os requisitos estabelecidos na legisla&ccedil;&atilde;o vigente, e adota as melhores pr&aacute;ticas de mercado a fim de garantir a prote&ccedil;&atilde;o e privacidade dos seus dados pessoais.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>SEUS DIREITOS COMO TITULAR DOS DADOS PESSOAIS&nbsp;</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">A transpar&ecirc;ncia sobre o tratamento dos seus dados pessoais &eacute; prioridade da Preservando. Al&eacute;m das informa&ccedil;&otilde;es disponibilizadas nesta Pol&iacute;tica de Privacidade, voc&ecirc; pode tamb&eacute;m exercer os direitos previstos da Lei Geral de Prote&ccedil;&atilde;o de Dados, entre elas:</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Confirma&ccedil;&atilde;o da exist&ecirc;ncia de tratamento de dados pessoais;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Acesso aos dados pessoais;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Revoga&ccedil;&atilde;o do consentimento;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Corre&ccedil;&atilde;o de dados pessoais incompletos, inexatos ou desatualizados;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Elimina&ccedil;&atilde;o dos dados pessoais tratados com o consentimento ou desnecess&aacute;rios, excessivos ou quando entender que algum ponto da LGPD n&atilde;o foi atendido;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&atilde;o sobre as hip&oacute;teses e com quais empresas, parceiros e outras institui&ccedil;&otilde;es podemos compartilhar, ou receber dados pessoais referente &agrave; voc&ecirc;;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Informa&ccedil;&atilde;o sobre a possibilidade de n&atilde;o fornecer consentimento e sobre as consequ&ecirc;ncias da negativa, quando aplic&aacute;vel;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Todas as solicita&ccedil;&otilde;es ser&atilde;o de tratadas de forma gratuita, e ser&atilde;o submetidas a uma pr&eacute;via avalia&ccedil;&atilde;o da sua identidade e da viabilidade do atendimento, a fim de cumprir com eventuais obriga&ccedil;&otilde;es que impe&ccedil;am o completo atendimento das requisi&ccedil;&otilde;es dos titulares de direito.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>RETEN&Ccedil;&Atilde;O E EXCLUS&Atilde;O DOS SEUS DADOS PESSOAIS&nbsp;</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">N&oacute;s tratamos seus dados pessoais com elevados n&iacute;veis de prote&ccedil;&atilde;o e garantindo sua privacidade, durante todo o per&iacute;odo que voc&ecirc; for nosso cliente, navegando em nosso site e utilizando nossos servi&ccedil;os, ou potencial cliente com quem dividimos nossas ofertas de produtos e servi&ccedil;os.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Quando aplic&aacute;vel, e mesmo se voc&ecirc; optar por excluir seus dados pessoais da nossa base de cadastro, a Preservando poder&aacute; reter alguns ou todos os seus dados pessoais por per&iacute;odos adicionais para cumprimento de obriga&ccedil;&otilde;es leais ou regulat&oacute;rias, para o exerc&iacute;cio regular de direitos da Preservando, eventuais a&ccedil;&otilde;es judiciais, fins de auditoria de diversas naturezas, ou outros prazos definidos e fundamentados por bases legais que justifiquem a reten&ccedil;&atilde;o destes dados.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>ALTERA&Ccedil;&Otilde;ES DESTA POL&Iacute;TICA DE PRIVACIDADE</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Estamos constantemente buscando aprimorar a experi&ecirc;ncia de nossos clientes. Assim, nossas pr&aacute;ticas de tratamento de dados pessoais poder&atilde;o sofrer altera&ccedil;&otilde;es com a inclus&atilde;o de novas funcionalidades e servi&ccedil;os.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Valorizamos a transpar&ecirc;ncia no modo em que tratamos seus dados pessoais. Toda vez que alguma condi&ccedil;&atilde;o relevante desta Pol&iacute;tica de Privacidade for alterada, essas altera&ccedil;&otilde;es ser&atilde;o v&aacute;lidas, eficazes e vinculadas ap&oacute;s a nova vers&atilde;o a ser publicada em nosso site. Estas altera&ccedil;&otilde;es ser&atilde;o comunicadas por meio de um dos canais disponibilizados por voc&ecirc; durante o seu cadastro (e-mail, SMS, WhatsApp e outros).</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><br>&nbsp;</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;"><strong>FALE CONOSCO</strong></p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Sempre que voc&ecirc; tiver alguma d&uacute;vida sobe esta Pol&iacute;tica de Privacidade, mesmo ap&oacute;s sua leitura, ou precisar interagir conosco sobre assuntos envolvendo os seus dados pessoais, poder&aacute; faz&ecirc;-lo: por meio dos nossos canais de atendimento dispon&iacute;veis em <u><a href="http://www.preservando.com.br/">www.preservando.com.br</a></u>, solicitando as op&ccedil;&otilde;es sobre a privacidade dos seus dados pessoais, sempre que dispon&iacute;vel; ou pelo e-mail <u><a href="mailto:contato@preservando.com.br">contato@preservando.com.br</a></u>.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Recomendamos que verifiquem a vers&atilde;o atualizada desta Pol&iacute;tica de Privacidade sempre que navegarem em nosso site.</p>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 108%;">Estamos sempre &agrave; disposi&ccedil;&atilde;o para esclarecer suas d&uacute;vidas e colocar voc&ecirc; no controle dos seus dados pessoais. Contem conosco para mant&ecirc;-los informados!</p>
    </div>
@endsection